name = "FranklinParser"
uuid = "796511e7-1510-466f-ad0c-1823c64bcafa"
authors = ["Thibaut Lienart <tlienart@me.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
DocStringExtensions = "0.8"
OrderedCollections = "1.3"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
