name = "FranklinParser"
uuid = "796511e7-1510-466f-ad0c-1823c64bcafa"
authors = ["Thibaut Lienart <tlienart@me.com>"]
version = "0.1.2"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
DocStringExtensions = "0.8"
OrderedCollections = "1.3"
CommonMark = "0.7.1"
julia = "1.5"

[extras]
CommonMark = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CommonMark", "Pkg"]
